server:
  port: 8080
  servlet:
    session:
      timeout: 300m
spring:
  mvc:
    favicon:
      enabled: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/storejj?useUnicode=true&characterEncoding=utf-8&useSSL=true&useTimezone=true&serverTimezone=GMT%2B8
    username: root
    password: root
  thymeleaf:
    prefix: classpath:/templates
    check-template-location: false
    suffix: .html
    encoding: UTF-8
    mode: HTML
    cache: false
    enabled: true
    servlet:
      content-type: text/html

  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
  servlet:
    multipart:
      max-file-size: 52428800
      max-request-size: 52428800

  mail:
      port: 25
      host:
      username:
      password:
      default-encoding: UTF-8
      protocol: smtp
      test-connection: false

mybatis:
  mapper-locations: classpath:com/cy/**/mapper/*.xml
  type-aliases-package: com.cy.*.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true #下划线改小驼峰

debug: false

#自定义变量
system:
  account: System
  password: 666

  html:
    admin: /admin/
    web: /web/meghna/

  upload:
    path: C:/www/upload/

  pagesize: 15

  session:
    admin:
      account: ADMIN_ACCOUNT
      id: ADMIN_ID
      group: ADMIN_GROUP
      session: ADMIN_SESSION
      auth: ADMIN_AUTH
      vercode: ADMIN_VERCODE
    user:
      account: USER_ACCOUNT
      id: USER_ID
      session: USER_SESSION
      vercode: USER_VERCODE
      level: USER_LEVEL


web:
  title: 大平艺术





